### ISSUE TITLE
Pycharm .idea project settings directory not covered by .gitignore

### ISSUE THREAD

**Issue by bast0006** [Ikusaba-san/code-jam-5#4]
Currently the .gitignore file does not include a line for ".idea", which is the project configuration file for Pycharm and other Jetbrains ides. Since two of us are using pycharm for this project, it should be added.

@Ikusaba-san can you do this?

**Comment by Ikusaba-san** [comment]
I had trouble making this work. For some reason it just flat out decided not to ignore the `.vscode` directory, and since it wasn't ignoring that I figured it wouldn't be ignoring the `.idea` directory either.

I'd probably just set up a global personal .gitignore since it probably shouldn't be committed on any project.
Something like this: https://stackoverflow.com/questions/7335420/global-git-ignore
